# Generated by Django 5.0 on 2025-03-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagarikk', '0002_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
